name: First Workflow
on: workflow_dispatch
jobs:
   first-job:
      runs-on: ubuntu-latest
      steps:
         -  name: Print Name
            run: echo "Learn Java Shankar"
            run: echo "Be expert"
